unit Teclado_Mouse;

interface

uses Classes;

//------------------
type
TRegra = record
  Chave: string;
  Valor: string;
end;
//------------------

//------------------------------------------------------------------------------
const Blood_Teclado: array[0..53] of TRegra = (
(Chave:'Move_Forward = '; Valor:'Move_Forward = "Up" "N/A"'),
(Chave:'Move_Backward = '; Valor:'Move_Backward = "Down" "N/A"'),
(Chave:'Turn_Left = '; Valor:'Turn_Left = "Left" "N/A"'),
(Chave:'Turn_Right = '; Valor:'Turn_Right = "Right" "N/A"'),
(Chave:'Turn_Around = '; Valor:'Turn_Around = "N/A" "N/A"'),
(Chave:'Strafe = '; Valor:'Strafe = "LAlt" "RAlt"'),
(Chave:'Strafe_Left = '; Valor:'Strafe_Left = "N/A" "N/A"'),
(Chave:'Strafe_Right = '; Valor:'Strafe_Right = "N/A" "N/A"'),
(Chave:'Jump = '; Valor:'Jump = "A" "N/A"'),
(Chave:'Crouch = '; Valor:'Crouch = "Z" "N/A"'),
(Chave:'Run = '; Valor:'Run = "LShift" "RShift"'),
(Chave:'AutoRun = '; Valor:'AutoRun = "CapLck" "N/A"'),
(Chave:'Open = '; Valor:'Open = "Space" "N/A"'),
(Chave:'Weapon_Fire = '; Valor:'Weapon_Fire = "LCtrl" "RCtrl"'),
(Chave:'Weapon_Special_Fire = '; Valor:'Weapon_Special_Fire = "X" "N/A"'),
(Chave:'Aim_Up = '; Valor:'Aim_Up = "N/A" "N/A"'),
(Chave:'Aim_Down = '; Valor:'Aim_Down = "N/A" "N/A"'),
(Chave:'Aim_Center = '; Valor:'Aim_Center = "N/A" "N/A"'),
(Chave:'Look_Up = '; Valor:'Look_Up = "N/A" "N/A"'),
(Chave:'Look_Down = '; Valor:'Look_Down = "N/A" "N/A"'),
(Chave:'Tilt_Left = '; Valor:'Tilt_Left = "N/A" "N/A"'),
(Chave:'Tilt_Right = '; Valor:'Tilt_Right = "N/A" "N/A"'),
(Chave:'Weapon_1 = '; Valor:'Weapon_1 = "1" "N/A"'),
(Chave:'Weapon_2 = '; Valor:'Weapon_2 = "2" "N/A"'),
(Chave:'Weapon_3 = '; Valor:'Weapon_3 = "3" "N/A"'),
(Chave:'Weapon_4 = '; Valor:'Weapon_4 = "4" "N/A"'),
(Chave:'Weapon_5 = '; Valor:'Weapon_5 = "5" "N/A"'),
(Chave:'Weapon_6 = '; Valor:'Weapon_6 = "6" "N/A"'),
(Chave:'Weapon_7 = '; Valor:'Weapon_7 = "7" "N/A"'),
(Chave:'Weapon_8 = '; Valor:'Weapon_8 = "8" "N/A"'),
(Chave:'Weapon_9 = '; Valor:'Weapon_9 = "9" "N/A"'),
(Chave:'Weapon_10 = '; Valor:'Weapon_10 = "0" "N/A"'),
(Chave:'Inventory_Use = '; Valor:'Inventory_Use = "Enter" "N/A"'),
(Chave:'Inventory_Left = '; Valor:'Inventory_Left = "[" "N/A"'),
(Chave:'Inventory_Right = '; Valor:'Inventory_Right = "]" "N/A"'),
(Chave:'Map_Toggle = '; Valor:'Map_Toggle = "Tab" "N/A"'),
(Chave:'Map_Follow_Mode = '; Valor:'Map_Follow_Mode = "F" "N/A"'),
(Chave:'Shrink_Screen = '; Valor:'Shrink_Screen = "-" "N/A"'),
(Chave:'Enlarge_Screen = '; Valor:'Enlarge_Screen = "=" "N/A"'),
(Chave:'Send_Message = '; Valor:'Send_Message = "T" "N/A"'),
(Chave:'See_Coop_View = '; Valor:'See_Coop_View = "K" "N/A"'),
(Chave:'See_Chase_View = '; Valor:'See_Chase_View = "F7" "N/A"'),
(Chave:'Mouse_Aiming = '; Valor:'Mouse_Aiming = "U" "N/A"'),
(Chave:'Toggle_Crosshair = '; Valor:'Toggle_Crosshair = "I" "N/A"'),
(Chave:'Next_Weapon = '; Valor:'Next_Weapon = "N/A" "N/A"'),
(Chave:'Previous_Weapon = '; Valor:'Previous_Weapon = "N/A" "N/A"'),
(Chave:'Holster_Weapon = '; Valor:'Holster_Weapon = "N/A" "N/A"'),
(Chave:'Show_Opponents_Weapon = '; Valor:'Show_Opponents_Weapon = "W" "N/A"'),
(Chave:'BeastVision = '; Valor:'BeastVision = "B" "N/A"'),
(Chave:'CrystalBall = '; Valor:'CrystalBall = "C" "N/A"'),
(Chave:'JumpBoots = '; Valor:'JumpBoots = "J" "N/A"'),
(Chave:'MedKit = '; Valor:'MedKit = "M" "N/A"'),
(Chave:'ProximityBombs = '; Valor:'ProximityBombs = "P" "N/A"'),
(Chave:'RemoteBombs = '; Valor:'RemoteBombs = "R" "N/A"')
);
//------------------------------------------------------------------------------
const Duke_Teclado: array[0..51] of TRegra = (
(Chave:'Move_Forward = '; Valor:'Move_Forward = "Up" ""'),
(Chave:'Move_Backward = '; Valor:'Move_Backward = "Down" ""'),
(Chave:'Turn_Left = '; Valor:'Turn_Left = "Left" ""'),
(Chave:'Turn_Right = '; Valor:'Turn_Right = "Right" ""'),
(Chave:'Strafe = '; Valor:'Strafe = "LAlt" "RAlt"'),
(Chave:'Fire = '; Valor:'Fire = "LCtrl" "RCtrl"'),
(Chave:'Open = '; Valor:'Open = "Space" ""'),
(Chave:'Run = '; Valor:'Run = "LShift" "RShift"'),
(Chave:'AutoRun = '; Valor:'AutoRun = "CapLck" ""'),
(Chave:'Jump = '; Valor:'Jump = "A" ""'),
(Chave:'Crouch = '; Valor:'Crouch = "Z" ""'),
(Chave:'Look_Up = '; Valor:'Look_Up = "" ""'),
(Chave:'Look_Down = '; Valor:'Look_Down = "" ""'),
(Chave:'Look_Left = '; Valor:'Look_Left = "" ""'),
(Chave:'Look_Right = '; Valor:'Look_Right = "" ""'),
(Chave:'Strafe_Left = '; Valor:'Strafe_Left = "," ""'),
(Chave:'Strafe_Right = '; Valor:'Strafe_Right = "." ""'),
(Chave:'Aim_Up = '; Valor:'Aim_Up = "" ""'),
(Chave:'Aim_Down = '; Valor:'Aim_Down = "" ""'),
(Chave:'Weapon_1 = '; Valor:'Weapon_1 = "1" ""'),
(Chave:'Weapon_2 = '; Valor:'Weapon_2 = "2" ""'),
(Chave:'Weapon_3 = '; Valor:'Weapon_3 = "3" ""'),
(Chave:'Weapon_4 = '; Valor:'Weapon_4 = "4" ""'),
(Chave:'Weapon_5 = '; Valor:'Weapon_5 = "5" ""'),
(Chave:'Weapon_6 = '; Valor:'Weapon_6 = "6" ""'),
(Chave:'Weapon_7 = '; Valor:'Weapon_7 = "7" ""'),
(Chave:'Weapon_8 = '; Valor:'Weapon_8 = "8" ""'),
(Chave:'Weapon_9 = '; Valor:'Weapon_9 = "9" ""'),
(Chave:'Weapon_10 = '; Valor:'Weapon_10 = "0" ""'),
(Chave:'Inventory = '; Valor:'Inventory = "Enter" ""'),
(Chave:'Inventory_Left = '; Valor:'Inventory_Left = "[" ""'),
(Chave:'Inventory_Right = '; Valor:'Inventory_Right = "]" ""'),
(Chave:'Holo_Duke = '; Valor:'Holo_Duke = "H" ""'),
(Chave:'Jetpack = '; Valor:'Jetpack = "J" ""'),
(Chave:'NightVision = '; Valor:'NightVision = "N" ""'),
(Chave:'MedKit = '; Valor:'MedKit = "M" ""'),
(Chave:'TurnAround = '; Valor:'TurnAround = "" ""'),
(Chave:'SendMessage = '; Valor:'SendMessage = "T" ""'),
(Chave:'Map = '; Valor:'Map = "Tab" ""'),
(Chave:'Shrink_Screen = '; Valor:'Shrink_Screen = "-" ""'),
(Chave:'Enlarge_Screen = '; Valor:'Enlarge_Screen = "=" ""'),
(Chave:'Center_View = '; Valor:'Center_View = "" ""'),
(Chave:'Holster_Weapon = '; Valor:'Holster_Weapon = "" ""'),
(Chave:'Show_Opponents_Weapon = '; Valor:'Show_Opponents_Weapon = "W" ""'),
(Chave:'Map_Follow_Mode = '; Valor:'Map_Follow_Mode = "F" ""'),
(Chave:'See_Coop_View = '; Valor:'See_Coop_View = "K" ""'),
(Chave:'Mouse_Aiming = '; Valor:'Mouse_Aiming = "U" ""'),
(Chave:'Toggle_Crosshair = '; Valor:'Toggle_Crosshair = "I" ""'),
(Chave:'Steroids = '; Valor:'Steroids = "R" ""'),
(Chave:'Quick_Kick = '; Valor:'Quick_Kick = "`" ""'),
(Chave:'Next_Weapon = '; Valor:'Next_Weapon = "" ""'),
(Chave:'Previous_Weapon = '; Valor:'Previous_Weapon = "" ""')
);
//------------------------------------------------------------------------------
const Shadow_Teclado: array[0..48] of TRegra = (
(Chave:'Move_Forward = '; Valor:'Move_Forward = "Up" ""'),
(Chave:'Move_Backward = '; Valor:'Move_Backward = "Down" ""'),
(Chave:'Turn_Left = '; Valor:'Turn_Left = "Left" ""'),
(Chave:'Turn_Right = '; Valor:'Turn_Right = "Right" ""'),
(Chave:'Strafe = '; Valor:'Strafe = "LAlt" "RAlt"'),
(Chave:'Fire = '; Valor:'Fire = "LCtrl" "RCtrl"'),
(Chave:'Open = '; Valor:'Open = "Space" ""'),
(Chave:'Run = '; Valor:'Run = "LShift" "RShift"'),
(Chave:'AutoRun = '; Valor:'AutoRun = "CapLck" ""'),
(Chave:'Jump = '; Valor:'Jump = "A" ""'),
(Chave:'Crouch = '; Valor:'Crouch = "Z" ""'),
(Chave:'Look_Up = '; Valor:'Look_Up = "" ""'),
(Chave:'Look_Down = '; Valor:'Look_Down = "" ""'),
(Chave:'Strafe_Left = '; Valor:'Strafe_Left = "," ""'),
(Chave:'Strafe_Right = '; Valor:'Strafe_Right = "." ""'),
(Chave:'Aim_Up = '; Valor:'Aim_Up = "" ""'),
(Chave:'Aim_Down = '; Valor:'Aim_Down = "" ""'),
(Chave:'Weapon_1 = '; Valor:'Weapon_1 = "1" ""'),
(Chave:'Weapon_2 = '; Valor:'Weapon_2 = "2" ""'),
(Chave:'Weapon_3 = '; Valor:'Weapon_3 = "3" ""'),
(Chave:'Weapon_4 = '; Valor:'Weapon_4 = "4" ""'),
(Chave:'Weapon_5 = '; Valor:'Weapon_5 = "5" ""'),
(Chave:'Weapon_6 = '; Valor:'Weapon_6 = "6" ""'),
(Chave:'Weapon_7 = '; Valor:'Weapon_7 = "7" ""'),
(Chave:'Weapon_8 = '; Valor:'Weapon_8 = "8" ""'),
(Chave:'Weapon_9 = '; Valor:'Weapon_9 = "9" ""'),
(Chave:'Weapon_10 = '; Valor:'Weapon_10 = "0" ""'),
(Chave:'Inventory = '; Valor:'Inventory = "Enter" ""'),
(Chave:'Inventory_Left = '; Valor:'Inventory_Left = "[" ""'),
(Chave:'Inventory_Right = '; Valor:'Inventory_Right = "]" ""'),
(Chave:'Med_Kit = '; Valor:'Med_Kit = "M" ""'),
(Chave:'Smoke_Bomb = '; Valor:'Smoke_Bomb = "S" ""'),
(Chave:'Night_Vision = '; Valor:'Night_Vision = "N" ""'),
(Chave:'Gas_Bomb = '; Valor:'Gas_Bomb = "G" ""'),
(Chave:'Flash_Bomb = '; Valor:'Flash_Bomb = "F" ""'),
(Chave:'Caltrops = '; Valor:'Caltrops = "C" ""'),
(Chave:'TurnAround = '; Valor:'TurnAround = "" ""'),
(Chave:'SendMessage = '; Valor:'SendMessage = "T" ""'),
(Chave:'Map = '; Valor:'Map = "Tab" ""'),
(Chave:'Shrink_Screen = '; Valor:'Shrink_Screen = "-" ""'),
(Chave:'Enlarge_Screen = '; Valor:'Enlarge_Screen = "=" ""'),
(Chave:'Center_View = '; Valor:'Center_View = "" ""'),
(Chave:'Holster_Weapon = '; Valor:'Holster_Weapon = "" ""'),
(Chave:'Map_Follow_Mode = '; Valor:'Map_Follow_Mode = "F" ""'),
(Chave:'See_Co_Op_View = '; Valor:'See_Co_Op_View = "K" ""'),
(Chave:'Mouse_Aiming = '; Valor:'Mouse_Aiming = "U" ""'),
(Chave:'Toggle_Crosshair = '; Valor:'Toggle_Crosshair = "I" ""'),
(Chave:'Next_Weapon = '; Valor:'Next_Weapon = "" ""'),
(Chave:'Previous_Weapon = '; Valor:'Previous_Weapon = "" ""')
);
//------------------------------------------------------------------------------
const Blood_Mouse: array[0..53] of TRegra = (
  (Chave:'Move_Forward = '; Valor:'Move_Forward = "W" "N/A"'),
  (Chave:'Move_Backward = '; Valor:'Move_Backward = "S" "N/A"'),
  (Chave:'Turn_Left = '; Valor:'Turn_Left = "N/A" "N/A"'),
  (Chave:'Turn_Right = '; Valor:'Turn_Right = "N/A" "N/A"'),
  (Chave:'Turn_Around = '; Valor:'Turn_Around = "N/A" "N/A"'),
  (Chave:'Strafe = '; Valor:'Strafe = "N/A" "N/A"'),
  (Chave:'Strafe_Left = '; Valor:'Strafe_Left = "A" "N/A"'),
  (Chave:'Strafe_Right = '; Valor:'Strafe_Right = "D" "N/A"'),
  (Chave:'Jump = '; Valor:'Jump = "Space" "N/A"'),
  (Chave:'Crouch = '; Valor:'Crouch = "C" "N/A"'),
  (Chave:'Run = '; Valor:'Run = "LShift" "RShift"'),
  (Chave:'AutoRun = '; Valor:'AutoRun = "CapLck" "N/A"'),
  (Chave:'Open = '; Valor:'Open = "E" "N/A"'),
  (Chave:'Weapon_Fire = '; Valor:'Weapon_Fire = "LCtrl" "RCtrl"'),
  (Chave:'Weapon_Special_Fire = '; Valor:'Weapon_Special_Fire = "X" "N/A"'),
  (Chave:'Aim_Up = '; Valor:'Aim_Up = "N/A" "N/A"'),
  (Chave:'Aim_Down = '; Valor:'Aim_Down = "N/A" "N/A"'),
  (Chave:'Aim_Center = '; Valor:'Aim_Center = "N/A" "N/A"'),
  (Chave:'Look_Up = '; Valor:'Look_Up = "N/A" "N/A"'),
  (Chave:'Look_Down = '; Valor:'Look_Down = "N/A" "N/A"'),
  (Chave:'Tilt_Left = '; Valor:'Tilt_Left = "N/A" "N/A"'),
  (Chave:'Tilt_Right = '; Valor:'Tilt_Right = "N/A" "N/A"'),
  (Chave:'Weapon_1 = '; Valor:'Weapon_1 = "1" "N/A"'),
  (Chave:'Weapon_2 = '; Valor:'Weapon_2 = "2" "N/A"'),
  (Chave:'Weapon_3 = '; Valor:'Weapon_3 = "3" "N/A"'),
  (Chave:'Weapon_4 = '; Valor:'Weapon_4 = "4" "N/A"'),
  (Chave:'Weapon_5 = '; Valor:'Weapon_5 = "5" "N/A"'),
  (Chave:'Weapon_6 = '; Valor:'Weapon_6 = "6" "N/A"'),
  (Chave:'Weapon_7 = '; Valor:'Weapon_7 = "7" "N/A"'),
  (Chave:'Weapon_8 = '; Valor:'Weapon_8 = "8" "N/A"'),
  (Chave:'Weapon_9 = '; Valor:'Weapon_9 = "9" "N/A"'),
  (Chave:'Weapon_10 = '; Valor:'Weapon_10 = "0" "N/A"'),
  (Chave:'Inventory_Use = '; Valor:'Inventory_Use = "Enter" "N/A"'),
  (Chave:'Inventory_Left = '; Valor:'Inventory_Left = "[" "N/A"'),
  (Chave:'Inventory_Right = '; Valor:'Inventory_Right = "]" "N/A"'),
  (Chave:'Map_Toggle = '; Valor:'Map_Toggle = "M" "N/A"'),
  (Chave:'Map_Follow_Mode = '; Valor:'Map_Follow_Mode = "N/A" "N/A"'),
  (Chave:'Shrink_Screen = '; Valor:'Shrink_Screen = "-" "N/A"'),
  (Chave:'Enlarge_Screen = '; Valor:'Enlarge_Screen = "=" "N/A"'),
  (Chave:'Send_Message = '; Valor:'Send_Message = "T" "N/A"'),
  (Chave:'See_Coop_View = '; Valor:'See_Coop_View = "K" "N/A"'),
  (Chave:'See_Chase_View = '; Valor:'See_Chase_View = "N/A" "N/A"'),
  (Chave:'Mouse_Aiming = '; Valor:'Mouse_Aiming = "U" "N/A"'),
  (Chave:'Toggle_Crosshair = '; Valor:'Toggle_Crosshair = "N/A" "N/A"'),
  (Chave:'Next_Weapon = '; Valor:'Next_Weapon = "N/A" "N/A"'),
  (Chave:'Previous_Weapon = '; Valor:'Previous_Weapon = "N/A" "N/A"'),
  (Chave:'Holster_Weapon = '; Valor:'Holster_Weapon = "N/A" "N/A"'),
  (Chave:'Show_Opponents_Weapon = '; Valor:'Show_Opponents_Weapon = "N/A" "N/A"'),
  (Chave:'BeastVision = '; Valor:'BeastVision = "N/A" "N/A"'),
  (Chave:'CrystalBall = '; Valor:'CrystalBall = "N/A" "N/A"'),
  (Chave:'JumpBoots = '; Valor:'JumpBoots = "N/A" "N/A"'),
  (Chave:'MedKit = '; Valor:'MedKit = "N/A" "N/A"'),
  (Chave:'ProximityBombs = '; Valor:'ProximityBombs = "N/A" "N/A"'),
  (Chave:'RemoteBombs = '; Valor:'RemoteBombs = "N/A" "N/A"')
);
//------------------------------------------------------------------------------
const Duke_Mouse: array[0..51] of TRegra = (
  (Chave:'Move_Forward = '; Valor:'Move_Forward = "W" ""'),
  (Chave:'Move_Backward = '; Valor:'Move_Backward = "S" ""'),
  (Chave:'Turn_Left = '; Valor:'Turn_Left = "" ""'),
  (Chave:'Turn_Right = '; Valor:'Turn_Right = "" ""'),
  (Chave:'Strafe = '; Valor:'Strafe = "" ""'),
  (Chave:'Fire = '; Valor:'Fire = "LCtrl" "RCtrl"'),
  (Chave:'Open = '; Valor:'Open = "E" ""'),
  (Chave:'Run = '; Valor:'Run = "LShift" "RShift"'),
  (Chave:'AutoRun = '; Valor:'AutoRun = "CapLck" ""'),
  (Chave:'Jump = '; Valor:'Jump = "Space" ""'),
  (Chave:'Crouch = '; Valor:'Crouch = "C" ""'),
  (Chave:'Look_Up = '; Valor:'Look_Up = "" ""'),
  (Chave:'Look_Down = '; Valor:'Look_Down = "" ""'),
  (Chave:'Look_Left = '; Valor:'Look_Left = "" ""'),
  (Chave:'Look_Right = '; Valor:'Look_Right = "" ""'),
  (Chave:'Strafe_Left = '; Valor:'Strafe_Left = "A" ""'),
  (Chave:'Strafe_Right = '; Valor:'Strafe_Right = "D" ""'),
  (Chave:'Aim_Up = '; Valor:'Aim_Up = "" ""'),
  (Chave:'Aim_Down = '; Valor:'Aim_Down = "" ""'),
  (Chave:'Weapon_1 = '; Valor:'Weapon_1 = "1" ""'),
  (Chave:'Weapon_2 = '; Valor:'Weapon_2 = "2" ""'),
  (Chave:'Weapon_3 = '; Valor:'Weapon_3 = "3" ""'),
  (Chave:'Weapon_4 = '; Valor:'Weapon_4 = "4" ""'),
  (Chave:'Weapon_5 = '; Valor:'Weapon_5 = "5" ""'),
  (Chave:'Weapon_6 = '; Valor:'Weapon_6 = "6" ""'),
  (Chave:'Weapon_7 = '; Valor:'Weapon_7 = "7" ""'),
  (Chave:'Weapon_8 = '; Valor:'Weapon_8 = "8" ""'),
  (Chave:'Weapon_9 = '; Valor:'Weapon_9 = "9" ""'),
  (Chave:'Weapon_10 = '; Valor:'Weapon_10 = "0" ""'),
  (Chave:'Inventory = '; Valor:'Inventory = "I" ""'),
  (Chave:'Inventory_Left = '; Valor:'Inventory_Left = "[" ""'),
  (Chave:'Inventory_Right = '; Valor:'Inventory_Right = "]" ""'),
  (Chave:'Holo_Duke = '; Valor:'Holo_Duke = "" ""'),
  (Chave:'Jetpack = '; Valor:'Jetpack = "" ""'),
  (Chave:'NightVision = '; Valor:'NightVision = "" ""'),
  (Chave:'MedKit = '; Valor:'MedKit = "" ""'),
  (Chave:'TurnAround = '; Valor:'TurnAround = "" ""'),
  (Chave:'SendMessage = '; Valor:'SendMessage = "T" ""'),
  (Chave:'Map = '; Valor:'Map = "M" ""'),
  (Chave:'Shrink_Screen = '; Valor:'Shrink_Screen = "-" ""'),
  (Chave:'Enlarge_Screen = '; Valor:'Enlarge_Screen = "=" ""'),
  (Chave:'Center_View = '; Valor:'Center_View = "" ""'),
  (Chave:'Holster_Weapon = '; Valor:'Holster_Weapon = "" ""'),
  (Chave:'Show_Opponents_Weapon = '; Valor:'Show_Opponents_Weapon = "" ""'),
  (Chave:'Map_Follow_Mode = '; Valor:'Map_Follow_Mode = "" ""'),
  (Chave:'See_Coop_View = '; Valor:'See_Coop_View = "K" ""'),
  (Chave:'Mouse_Aiming = '; Valor:'Mouse_Aiming = "U" ""'),
  (Chave:'Toggle_Crosshair = '; Valor:'Toggle_Crosshair = "" ""'),
  (Chave:'Steroids = '; Valor:'Steroids = "" ""'),
  (Chave:'Quick_Kick = '; Valor:'Quick_Kick = "`" ""'),
  (Chave:'Next_Weapon = '; Valor:'Next_Weapon = "" ""'),
  (Chave:'Previous_Weapon = '; Valor:'Previous_Weapon = "" ""')
);
//------------------------------------------------------------------------------
const Shadow_Mouse: array[0..48] of TRegra = (
  (Chave:'Move_Forward = '; Valor:'Move_Forward = "W" ""'),
  (Chave:'Move_Backward = '; Valor:'Move_Backward = "S" ""'),
  (Chave:'Turn_Left = '; Valor:'Turn_Left = "" ""'),
  (Chave:'Turn_Right = '; Valor:'Turn_Right = "" ""'),
  (Chave:'Strafe = '; Valor:'Strafe = "" ""'),
  (Chave:'Fire = '; Valor:'Fire = "LCtrl" "RCtrl"'),
  (Chave:'Open = '; Valor:'Open = "E" ""'),
  (Chave:'Run = '; Valor:'Run = "LShift" "RShift"'),
  (Chave:'AutoRun = '; Valor:'AutoRun = "CapLck" ""'),
  (Chave:'Jump = '; Valor:'Jump = "Space" ""'),
  (Chave:'Crouch = '; Valor:'Crouch = "C" ""'),
  (Chave:'Look_Up = '; Valor:'Look_Up = "" ""'),
  (Chave:'Look_Down = '; Valor:'Look_Down = "" ""'),
  (Chave:'Strafe_Left = '; Valor:'Strafe_Left = "A" ""'),
  (Chave:'Strafe_Right = '; Valor:'Strafe_Right = "D" ""'),
  (Chave:'Aim_Up = '; Valor:'Aim_Up = "" ""'),
  (Chave:'Aim_Down = '; Valor:'Aim_Down = "" ""'),
  (Chave:'Weapon_1 = '; Valor:'Weapon_1 = "1" ""'),
  (Chave:'Weapon_2 = '; Valor:'Weapon_2 = "2" ""'),
  (Chave:'Weapon_3 = '; Valor:'Weapon_3 = "3" ""'),
  (Chave:'Weapon_4 = '; Valor:'Weapon_4 = "4" ""'),
  (Chave:'Weapon_5 = '; Valor:'Weapon_5 = "5" ""'),
  (Chave:'Weapon_6 = '; Valor:'Weapon_6 = "6" ""'),
  (Chave:'Weapon_7 = '; Valor:'Weapon_7 = "7" ""'),
  (Chave:'Weapon_8 = '; Valor:'Weapon_8 = "8" ""'),
  (Chave:'Weapon_9 = '; Valor:'Weapon_9 = "9" ""'),
  (Chave:'Weapon_10 = '; Valor:'Weapon_10 = "0" ""'),
  (Chave:'Inventory = '; Valor:'Inventory = "I" ""'),
  (Chave:'Inventory_Left = '; Valor:'Inventory_Left = "[" ""'),
  (Chave:'Inventory_Right = '; Valor:'Inventory_Right = "]" ""'),
  (Chave:'Med_Kit = '; Valor:'Med_Kit = "" ""'),
  (Chave:'Smoke_Bomb = '; Valor:'Smoke_Bomb = "" ""'),
  (Chave:'Night_Vision = '; Valor:'Night_Vision = "" ""'),
  (Chave:'Gas_Bomb = '; Valor:'Gas_Bomb = "" ""'),
  (Chave:'Flash_Bomb = '; Valor:'Flash_Bomb = "" ""'),
  (Chave:'Caltrops = '; Valor:'Caltrops = "" ""'),
  (Chave:'TurnAround = '; Valor:'TurnAround = "" ""'),
  (Chave:'SendMessage = '; Valor:'SendMessage = "T" ""'),
  (Chave:'Map = '; Valor:'Map = "M" ""'),
  (Chave:'Shrink_Screen = '; Valor:'Shrink_Screen = "-" ""'),
  (Chave:'Enlarge_Screen = '; Valor:'Enlarge_Screen = "=" ""'),
  (Chave:'Center_View = '; Valor:'Center_View = "" ""'),
  (Chave:'Holster_Weapon = '; Valor:'Holster_Weapon = "" ""'),
  (Chave:'Map_Follow_Mode = '; Valor:'Map_Follow_Mode = "" ""'),
  (Chave:'See_Co_Op_View = '; Valor:'See_Co_Op_View = "K" ""'),
  (Chave:'Mouse_Aiming = '; Valor:'Mouse_Aiming = "U" ""'),
  (Chave:'Toggle_Crosshair = '; Valor:'Toggle_Crosshair = "" ""'),
  (Chave:'Next_Weapon = '; Valor:'Next_Weapon = "" ""'),
  (Chave:'Previous_Weapon = '; Valor:'Previous_Weapon = "" ""')
);
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
procedure AplicaRegras(Linha: Integer; const Regras: array of TRegra; Arquivo: TStrings);
procedure AplicaRegraValor(i: Integer; const Chave, Valor: string; Linhas: TStrings);
//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------

implementation

//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
procedure AplicaRegras(Linha: Integer; const Regras: array of TRegra; Arquivo: TStrings);
var
j: Integer;
begin
  for j := Low(Regras) to High(Regras) do
    if Pos(Regras[j].Chave, Arquivo[Linha]) = 1 then
      Arquivo[Linha] := Regras[j].Valor;
end;
//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
procedure AplicaRegraValor(i: Integer; const Chave, Valor: string; Linhas: TStrings);
begin
  if Pos(Chave, Linhas[i]) = 1 then
    Linhas[i] := Valor;
end;
//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
end.
 